---
version: "2.3"

services:
    iu9lab-container:
        image: stewkk/testsuite-golang
        environment: []
        volumes:
            - .:/iu9lab:rw
            - /var/cache/iu9lab-web/modules:/go/pkg/mod
            - /var/cache/iu9lab-web/go-build:/root/.cache/go-build
        ports:
            - 8080:8080
        working_dir: /iu9lab
