/**
* Lab generator API.
* Can be used to generate laboratory works reports for BMSTU IU9. 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* DefaultApiImpl.h
*
* 
*/

#ifndef DEFAULT_API_IMPL_H_
#define DEFAULT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <DefaultApi.h>

#include "Inline_response_200.h"
#include "ReportData.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

class DefaultApiImpl : public io::swagger::server::api::DefaultApi {
public:
    DefaultApiImpl(Pistache::Address addr);
    ~DefaultApiImpl() { };

    void generate_report(const ReportData &reportData, Pistache::Http::ResponseWriter &response);
    void get_report_by_id(Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif