/**
* Lab generator API.
* Can be used to generate laboratory works reports for BMSTU IU9. 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "Error.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

Error::Error()
{
    m_Code = "";
    m_Message = "";
    
}

Error::~Error()
{
}

void Error::validate()
{
    // TODO: implement validation
}

nlohmann::json Error::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["code"] = ModelBase::toJson(m_Code);
    val["message"] = ModelBase::toJson(m_Message);
    

    return val;
}

void Error::fromJson(nlohmann::json& val)
{
    setCode(val.at("code"));
    setMessage(val.at("message"));
    
}


std::string Error::getCode() const
{
    return m_Code;
}
void Error::setCode(std::string value)
{
    m_Code = value;
    
}
std::string Error::getMessage() const
{
    return m_Message;
}
void Error::setMessage(std::string value)
{
    m_Message = value;
    
}

}
}
}
}

