/**
* Lab generator API.
* Can be used to generate laboratory works reports for BMSTU IU9. 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "Inline_response_200.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

Inline_response_200::Inline_response_200()
{
    m_Id = "";
    m_IdIsSet = false;
    m_Link = "";
    m_LinkIsSet = false;
    
}

Inline_response_200::~Inline_response_200()
{
}

void Inline_response_200::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_response_200::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_IdIsSet)
    {
        val["id"] = ModelBase::toJson(m_Id);
    }
    if(m_LinkIsSet)
    {
        val["link"] = ModelBase::toJson(m_Link);
    }
    

    return val;
}

void Inline_response_200::fromJson(nlohmann::json& val)
{
    if(val.find("id") != val.end())
    {
        setId(val.at("id"));
        
    }
    if(val.find("link") != val.end())
    {
        setLink(val.at("link"));
        
    }
    
}


std::string Inline_response_200::getId() const
{
    return m_Id;
}
void Inline_response_200::setId(std::string value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool Inline_response_200::idIsSet() const
{
    return m_IdIsSet;
}
void Inline_response_200::unsetId()
{
    m_IdIsSet = false;
}
std::string Inline_response_200::getLink() const
{
    return m_Link;
}
void Inline_response_200::setLink(std::string value)
{
    m_Link = value;
    m_LinkIsSet = true;
}
bool Inline_response_200::linkIsSet() const
{
    return m_LinkIsSet;
}
void Inline_response_200::unsetLink()
{
    m_LinkIsSet = false;
}

}
}
}
}

