/**
* Lab generator API.
* Can be used to generate laboratory works reports for BMSTU IU9. 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Inline_response_200.h
 *
 * 
 */

#ifndef Inline_response_200_H_
#define Inline_response_200_H_


#include "ModelBase.h"

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200
    : public ModelBase
{
public:
    Inline_response_200();
    virtual ~Inline_response_200();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_response_200 members

    /// <summary>
    /// Report UUID.
    /// </summary>
    std::string getId() const;
    void setId(std::string value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// Report URL.
    /// </summary>
    std::string getLink() const;
    void setLink(std::string value);
    bool linkIsSet() const;
    void unsetLink();

protected:
    std::string m_Id;
    bool m_IdIsSet;
    std::string m_Link;
    bool m_LinkIsSet;
};

}
}
}
}

#endif /* Inline_response_200_H_ */
