---
swagger: "2.0"
info:
  title: Lab generator API.
  description: |
    Can be used to generate laboratory works reports for BMSTU IU9.
  version: 0.0.1
host: 0.0.0.0:8080
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /generateReport:
    post:
      summary: Generate report in pdf format.
      description: |
        Generate report in pdf format. Returns link to created file.
      operationId: generateReport
      parameters:
        - in: body
          name: reportData
          schema:
            $ref: '#/definitions/ReportData'
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                description: Report UUID.
              link:
                type: string
                description: Report URL.
        default:
          $ref: '#/components/responses/default'
  /reports/{reportId}:
    get:
      summary: Get report by id.
      description: |
        Returns report pdf by id.
      operationId: getReportById
      produces:
        - application/pdf
      responses:
        200:
          description: OK
        default:
          $ref: '#/components/responses/default'
components:
  responses:
    default:
      description: Unexpected error.
      schema:
        $ref: '#/definitions/Error'

definitions:
  ReportData:
    type: object
    properties:
      workType:
        type: string
      title:
        type: string
      author:
        type: string
      teacher:
        type: string
      group:
        type: string
      course:
        type: integer
      labNumber:
        type: string
      body:
        type: string
      year:
        type: integer
    required:
      - workType
      - title
      - author
      - teacher
      - group
      - course
      - labNumber
      - body
      - year
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
