---
name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: setup golang cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: build dev image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: stewkk/testsuite-golang
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - name: check if Dockerfile changed
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dev-dockerfile:
            - 'Dockerfile'
    - name: push dev image
      if: steps.filter.outputs.dev-dockerfile == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: stewkk/testsuite-golang
        cache-from: type=local,src=/tmp/.buildx-cache-new
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    - name: setup python
      uses: actions/setup-python@v3
    - name: run pre-commit checks
      uses: pre-commit/action@v3.0.0
    - name: run tests
      run: make docker-test
