/**
* Lab generator API.
* Can be used to generate laboratory works reports for BMSTU IU9. 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * DefaultApi.h
 *
 * 
 */

#ifndef DefaultApi_H_
#define DefaultApi_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include "Inline_response_200.h"
#include "ReportData.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

class  DefaultApi {
public:
    DefaultApi(Pistache::Address addr);
    virtual ~DefaultApi() {};
    void init(size_t thr);
    void start();
    void shutdown();

    const std::string base = "/v1";

private:
    void setupRoutes();

    void generate_report_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_report_by_id_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void default_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Http::Endpoint> httpEndpoint;
    Pistache::Rest::Router router;


    /// <summary>
    /// Generate report in pdf format.
    /// </summary>
    /// <remarks>
    /// Generate report in pdf format. Returns link to created file. 
    /// </remarks>
    /// <param name="reportData"> (optional)</param>
    virtual void generate_report(const ReportData &reportData, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Get report by id.
    /// </summary>
    /// <remarks>
    /// Returns report pdf by id. 
    /// </remarks>
    virtual void get_report_by_id(Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* DefaultApi_H_ */

